apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhtml-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: footballprovtc
  template:
    metadata:
      labels:
        app: footballprovtc
    spec:
      containers:
      - name: footballprovtc
        image: sontungbk85/webcicd:8
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webhtml-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32000
  selector:
    app: footballprovtc